DROP DATABASE IF EXISTS BookStore;

CREATE DATABASE IF NOT EXISTS BookStore;
USE BookStore;

CREATE TABLE Card
(
  Id       INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
  IdClient INTEGER NOT NULL,
  IdBook   INTEGER NOT NULL,
  Status   BOOLEAN NOT NULL,

  PRIMARY KEY (Id)
);


CREATE TABLE Author
(
  Id      INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
  Name    VARCHAR(100) NOT NULL,
  Surname VARCHAR(100) NOT NULL,
  DOB     DATE         NOT NULL,

  PRIMARY KEY (Id)
);


CREATE TABLE Book
(
  Id          INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
  Name        VARCHAR(255) NOT NULL,
  Author      INTEGER      NOT NULL,
  Genre       VARCHAR(100),
  Language    VARCHAR(100),
  PubDate     DATE,
  Pages       INTEGER,
  Price       DECIMAL,
  Description LONGTEXT,

  PRIMARY KEY (Id)
);


CREATE TABLE Client
(
  Id       INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
  Name     VARCHAR(100) NOT NULL,
  Surname  VARCHAR(100) NOT NULL,
  Joined   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Phone    VARCHAR(10),
  Address  VARCHAR(200),
  Email    VARCHAR(200) NOT NULL,
  Password VARCHAR(15)  NOT NULL,

  PRIMARY KEY (Id)
);


ALTER TABLE Book ADD CONSTRAINT FK_IdAuthor FOREIGN KEY (Author) REFERENCES Author (Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT FK_IdBook FOREIGN KEY (IdBook) REFERENCES Book (Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT FK_IdClient FOREIGN KEY (IdClient) REFERENCES Client (Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

