DROP TABLE Author
IF EXISTS;

CREATE TABLE Author
(
  Id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  Name    VARCHAR(100)                                     NOT NULL,
  Surname VARCHAR(100)                                     NOT NULL,
  DOB     DATE                                             NOT NULL
);


CREATE TABLE Book
(
  Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  Name        VARCHAR(255)                                     NOT NULL,
  Author      INT                                              NOT NULL,
  Genre       VARCHAR(100),
  Language    VARCHAR(100),
  PubDate     DATE,
  Pages       INT,
  Price       DECIMAL,
  Description LONGVARCHAR,
  FOREIGN KEY (Author) REFERENCES Author (Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE Client
(
  Id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  Name     VARCHAR(100)                                     NOT NULL,
  Surname  VARCHAR(100)                                     NOT NULL,
  Phone    VARCHAR(10),
  Address  VARCHAR(200),
  Email    VARCHAR(200)                                     NOT NULL,
  Password VARCHAR(15)                                      NOT NULL
);


CREATE TABLE Card
(
  Id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL NOT NULL,
  IdClient INT                                  NOT NULL,
  IdBook   INT                                  NOT NULL,
  Status   BOOLEAN                              NOT NULL
);

ALTER TABLE Card ADD CONSTRAINT FK_IdBook FOREIGN KEY (IdBook) REFERENCES Book (Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT FK_IdClient FOREIGN KEY (IdClient) REFERENCES Client (Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

