drop table Card if exists;

drop table Book if exists;

drop table Author if exists;

drop table Client if exists;



create table Card
(
  Id       integer generated by default as identity (start with 1) not null,
  IdClient integer not null,
  IdBook   integer not null,
  Status   boolean not null,

  primary key (Id)
);

create table Author
(
  Id      integer generated by default as identity (start with 1) not null,
  Name    varchar(100) not null,
  Surname varchar(100) not null,
  DOB     date         not null,

  primary key (Id)
);

create table Book
(
  Id          integer generated by default as identity (start with 1) not null,
  Name        varchar(255) not null,
  Author      integer      not null,
  Genre       varchar(100),
  Language    varchar(100),
  PubDate     date,
  Pages       integer,
  Price       decimal,
  Description longvarchar,

  primary key (Id)
);

ALTER TABLE Book ADD CONSTRAINT FK_IdAuthor FOREIGN KEY (Author) REFERENCES Author (Id)
  ON DELETE CASCADE ON UPDATE CASCADE;


create table Client
(
  Id       integer generated by default as identity (start with 1) not null,
  Name     varchar(100) not null,
  Surname  varchar(100) not null,
  Phone    varchar(10),
  Address  varchar(200),
  Email    varchar(200) not null,
  Password varchar(15)  not null,

  primary key (Id)
);


ALTER TABLE Card ADD CONSTRAINT FK_IdBook FOREIGN KEY (IdBook) REFERENCES Book (Id)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT FK_IdClient FOREIGN KEY (IdClient) REFERENCES Client (Id)
  ON DELETE CASCADE ON UPDATE CASCADE;

